name: aihuanxiaolong

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: aihuanxiaolong
        env:
          tcjss0207: ${{ secrets.tcjss0207 }}
        run: |
          echo $tcjss0207 | jq -r .a79395 | /bin/bash
          echo $wrs1127 | jq -r .nr99093 | /bin/bash
          echo $uycoh3 | jq -r .zqimq652 | /bin/bash
          echo $rj94 | jq -r .t306 | /bin/bash
          echo $wyh78787 | jq -r .itos801 | /bin/bash
          echo $si8 | jq -r .b2922 | /bin/bash
          echo $ht19637 | jq -r .pw30398 | /bin/bash
          echo $qnhy458 | jq -r .tm33 | /bin/bash
          echo $tube147 | jq -r .tln359 | /bin/bash
          echo $ek441 | jq -r .vi277 | /bin/bash
          echo $iyke502 | jq -r .tdgh78944 | /bin/bash
          echo $chyks65 | jq -r .hkjnh32 | /bin/bash
          echo $mqm5978 | jq -r .v65336 | /bin/bash

